version: '3.8'
services:
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./server:/app
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        restart: always
        ports:
            - '80:80'
        depends_on:
            - server
